### ISSUE TITLE
Package "client" is shown in the top pypi packages, but it is not exist in PyPI (url https://pypi.org/project/client/ could not be found)?

### ISSUE THREAD

**Issue by vuduclyunitn** [hugovk/top-pypi-packages#16]

**Comment by hugovk** [comment]
What number is it currently listed at on https://hugovk.github.io/top-pypi-packages/?

**Comment by vuduclyunitn** [comment]
In the top 4000 packages, it is package number 3330.
![image](https://user-images.githubusercontent.com/32923740/107099590-5cc44a00-6812-11eb-9ff1-3f32ea374f7d.png)

**Comment by hugovk** [comment]
Strange!

My guess is it's something that has been removed from PyPI, probably due to spam/typosquatting or overlap with some stdlib name.

https://libraries.io/pypi/client says "This package has been marked as deprecated" and shows there was a single release on Mar 28, 2017.

Right now it's only in the 365-day list, not the 30-day list, so is no longer being downloaded.

The last tag that had it in the 30-day list was `2020.10`, suggesting it was removed during October 2020.

Hope that helps!
