### ISSUE TITLE
365 days json file (non-min) is empty at the moment

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [hugovk/top-pypi-packages#3]
The [this commit](https://github.com/hugovk/top-pypi-packages/commit/a3735577078869c54b617b0541e95222d7af27c1) emptied the [365days](https://github.com/hugovk/top-pypi-packages/blob/master/top-pypi-packages-365-days.json) file. 30 days file seems ok though.

**Comment by hugovk** [comment]
Thanks for the report!

Checking the logs, it had exceeded the quota after fetching the 30-day file because I had been testing some things out.

I've regenerated the 365-day files now, and both the minified and non-minified files have data:

* https://hugovk.github.io/top-pypi-packages/top-pypi-packages-365-days.json
* https://hugovk.github.io/top-pypi-packages/top-pypi-packages-365-days.min.json

I'll keep this issue open and double check it works as expected on the next automated run, this Friday. There should be enough quota by then :)

**Comment by hugovk** [comment]
Today the 30-day file updated, but it was out of data for the 365-day file. I've reset the 365 back to Wednesday and updated the scripts not to deploy if there's quota error in future. Will check again next Friday!

**Comment by verhovsky** [comment]
@hugovk still empty.

FYI, when I open https://bigquery.cloud.google.com/dataset/the-psf:pypi it says "Unable to find dataset: the-psf:pyp"

**Comment by hugovk** [comment]
Thanks for the info, I've updated the data files.

When I open https://bigquery.cloud.google.com/dataset/the-psf:pypi I see this:

![image](https://user-images.githubusercontent.com/1324225/57079364-d99ac980-6cf8-11e9-815b-9a5eac95231b.png)

**Comment by hugovk** [comment]
The files have been generated fine for the past few weeks, I'll close this now. Thanks again!
