### ISSUE TITLE
Used by "Are we PEP 740 yet?"

### ISSUE THREAD

**Issue by woodruffw** [hugovk/top-pypi-packages#40]
Hi @hugovk! Thanks a ton for this dataset, and also for [Free Threaded Wheels](https://hugovk.github.io/free-threaded-wheels/) as a living varian of the original Python Wheels tracker.

I'm opening this to link you to another site that uses your dataset: [Are we PEP 740 yet?](https://trailofbits.github.io/are-we-pep740-yet/), which tracks PEP 740 (attestations) adoption on PyPI.

If you're willing, we'd love to have this linked in your "Used by" section!

**Comment by hugovk** [comment]
Very nice :)

Added: https://github.com/hugovk/top-pypi-packages/commit/9f4e1196265f7fd8662ddb394fd4ba8253f31dbf

**Comment by hugovk** [comment]
The two I'm maintaining (Pillow and termcolor) are already green ✅

This is a good tracker, it's also more or less the same as a Trusted Publishing tracker :)

Some like Coverage.py haven't made a release since the default was flipped to opt-out. So hopefully a bunch will flip to green as their actions are updated and releases go out.

**Comment by woodruffw** [comment]
Thanks!

> This is a good tracker, it's also more or less the same as a Trusted Publishing tracker

Yep, exactly! In practice it should be a strong proxy for Trusted Publishing (although not a perfect one, since there are a few people doing the TP flow in their own code instead of using pypi-publish.)
